### PR TITLE
#81, #71, #72, #73 limit retry behavior in prepare_browser, workaroun…

### PR DESCRIPTION
**Pull request by bubenkoff**
Also a workaround for edge cleaning cookies

---
This change is [Reviewable](https://reviewable.io/reviews/pytest-dev/pytest-splinter/83)

### CODE REVIEW

**Comment by bubenkoff** [comment]
@pelme, does this work for you?

**Comment by pelme** [comment]
sorry, have not been able to test yet. will report back!

**Comment by bubenkoff** [comment]
@pelme, any update on this?

**Comment by Majsvaffla** [comment]
Can confirm that this solves problems with MS Edge #81. The browser doesn't crash or restart indefinitely.

**Comment by pelme** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pytest-dev/pytest-splinter/83)*

**Comment by pelme** [comment]
👍  Me and @Majsvaffla sits next to each other and this solves the problem!

Sorry for the slow response @bubenkoff. I have reviewed and accepted on reviewable. Give a 👍 and I can merge and put out a new release if you like.

(It is super annoying that edge cant be resized which breaks our tests, but that is another matter of course).

**Comment by bubenkoff** [comment]
1.8.0 is out

**Comment by pelme** [comment]
Very nice, thanks Anatoly!

**Pull request merged**
