### PR TITLE
Fix #52 -- Deprecated __multicall__ argument.

### LINKED ISSUE #52: pytest_runtest_makereport uses deprecated __multicall__ argument
Running pytest with pytest-splinter 1.7.0 installed causes the following pytest warning:

```'pytest_runtest_makereport' hook uses deprecated __multicall__ argument```

(pytest must be run with the `-rw` argument to see the actual warning message)

### PR DESCRIPTION
**Pull request by aaugustin**
Based on https://github.com/pytest-dev/pytest/commit/0253f7b8d5d66e3328f685ba12bedc10315c5e24.

### CODE REVIEW

**Comment by aaugustin** [comment]
Travis crashed for reasons obviously unrelated to this change.

This PR fixes the issue for me, although I'm nowhere near familiar enough with py.test to be sure the change is correct.

**Comment by aaugustin** [comment]
@bubenkoff How could I make it easier for you to assess and eventually merge this pull request?

**Comment by blueyed** [comment]
FWIW, I've just restarted the build, but it still failed in an unrelated way.

**Comment by firebirdberlin** [comment]
The failing "selenium-standalone install" seems to be a general problem of the test build. 
Despite this issue, I'd also like to see this PR merged. The _multicall__ argument is meant to be removed since pytest 2.8. Therefore the corresponding warning should not be ignored. 

Please note before merging, the return statement 
    return rep
no longer makes sense. The report is already yielded above.

**Comment by aaugustin** [comment]
I removed `return rep` and force-pushed (to keep just one commit).

**Comment by bubenkoff** [comment]
thanks!

**Pull request merged**
