### PR TITLE
escape screenshot paths for path separators

### LINKED ISSUE #64: Taking screenshot fails if name of the test contains "/" character (using pytest-bdd)
Hello,

I'm using:
```
platform linux2 -- Python 2.7.6, pytest-2.9.2, py-1.4.31, pluggy-0.3.1
plugins: bdd-2.16.1, splinter-1.7.3
```

My .feature file contains:
```
Scenario Outline: Application login page renders with proper title
  Given I'm visiting Application site
  When I go to the <page> page
  Then The page title should contain <title>

  Examples:
  | page        | title |
  | home/login  | login |
  | a           | b     |
```

I'm creating test cases with pytest_bdd:
```
scenarios('../features')
```

When test fails, it fails to take a screenshot, because generated test name contains ``/`` character:
```
WSPL504 None Could not save screenshot: [Errno 2] No such file or directory: '/home/kliput/Application/selenium-experiments/python/scenarios.test_lol/test_application_login_page_renders_with_proper_title[home/login-login]-browser.html'
```

The workaround is to use other chars and replace them with ``/`` inside tests, but it will be nice to escape ``/`` when creating path for screenshot file :)

### PR DESCRIPTION
**Pull request by bubenkoff**
closes #64

---
This change is [Reviewable](https://reviewable.io/reviews/pytest-dev/pytest-splinter/68)

### CODE REVIEW

**Comment by olegpidsadnyi** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pytest_splinter/plugin.py, line 453 \[r1\]](https://reviewable.io:443/reviews/pytest-dev/pytest-splinter/68#-KModOf8j-1t9rF-e0Kw:-KModOf9MyHPBvbfCWfR:2060346759) ([raw file](https://github.com/pytest-dev/pytest-splinter/blob/ab1b88b291b9994d82acef4a8ac4f5a025e769ad/pytest_splinter/plugin.py#L453)):*
> ```Python
>                 screenshot_dir = os.path.join(splinter_screenshot_dir, classname)
>                 screenshot_file_name_format = '{0}.{{format}}'.format(
>                     '{0}-{1}'.format(names[-1][:128 - len(name) - 5], name).replace(os.path.sep, '-')
> ```

linter fails here - line too long

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pytest-dev/pytest-splinter/68)*

**Comment by olegpidsadnyi** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[tests/test_plugin.py, line 200 \[r1\]](https://reviewable.io:443/reviews/pytest-dev/pytest-splinter/68#-KModcPhhyqpXxMLvrKD:-KModcPhhyqpXxMLvrKE:-1673599058) ([raw file](https://github.com/pytest-dev/pytest-splinter/blob/ab1b88b291b9994d82acef4a8ac4f5a025e769ad/tests/test_plugin.py#L200)):*
> ```Python
>     """.format(simple_page_content), "-vl", "-r w")
> 
>     content = testdir.tmpdir.join('test_browser_screenshot_escaped', 'test_screenshot[escaped-param]-browser.html').read()
> ```

no, actually in this file

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pytest-dev/pytest-splinter/68)*

**Comment by bubenkoff** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/test_plugin.py, line 200 \[r1\]](https://reviewable.io:443/reviews/pytest-dev/pytest-splinter/68#-KModcPhhyqpXxMLvrKD:-KMoe8zIM3hurwrHkjqQ:677588487) ([raw file](https://github.com/pytest-dev/pytest-splinter/blob/ab1b88b291b9994d82acef4a8ac4f5a025e769ad/tests/test_plugin.py#L200)):*
<details><summary><i>Previously, olegpidsadnyi (Oleg Pidsadnyi) wrote…</i></summary>
> no, actually in this file
</details>
done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pytest-dev/pytest-splinter/68)*

**Comment by olegpidsadnyi** [comment]
Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pytest-dev/pytest-splinter/68)*

**Comment by bubenkoff** [comment]
Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pytest-dev/pytest-splinter/68)*

**Comment by olegpidsadnyi** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pytest_splinter/plugin.py, line 453 \[r1\]](https://reviewable.io:443/reviews/pytest-dev/pytest-splinter/68#-KModOf8j-1t9rF-e0Kw:-KMofIVCR3kU2GhOyYB_:5173665) ([raw file](https://github.com/pytest-dev/pytest-splinter/blob/ab1b88b291b9994d82acef4a8ac4f5a025e769ad/pytest_splinter/plugin.py#L453)):*
<details><summary><i>Previously, olegpidsadnyi (Oleg Pidsadnyi) wrote…</i></summary>
> linter fails here - line too long
</details>
OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pytest-dev/pytest-splinter/68)*

**Pull request merged**
