### PR TITLE
Added Chrome headless support

### PR DESCRIPTION
**Pull request by miohtama**
This adds support for Chrome headless mode, so that Xvfb is no longer needed to run tests on headless environments (Travis).

Also there is a bug in Selenium that prevents Chrome window to be resized, causing confusing error messages: https://github.com/SeleniumHQ/selenium/issues/3508 - I simply decided to ignore the initial window resize for Chrome to workaround for this.

### CODE REVIEW

**Comment by iScrE4m** [comment]
This would be great to have merged in!

**Comment by ztane** [comment]
Please *get this option merged*, the whole project is pretty much unusable now.

**Comment by miohtama** [comment]
Hi! I think @ztane's concern might apply, as currently Splinter does not work headless Chrome (Travis et. al). How many beer and what would it take to get this merged?

**Comment by Qqwy** [comment]
Interestingly, just adding this fixture yourself:

```python
@pytest.fixture(scope='session')
def splinter_driver_kwargs():
    """Webdriver kwargs."""
    return {'headless': True}
```

does the same trick, and probably works for both Firefox and Chrome.

**Comment by bubenkoff** [comment]
@miohtama sorry for this taking so long, 1.9.0 is out!

**Pull request merged**
