### PR TITLE
Correct webdriver executable fixture in README

### PR DESCRIPTION
**Pull request by zsiciarz**
Took me a moment to discover that there's no such fixture as `splinter_driver_executable`, so here's a fix. I also clarified that it should return a *directory*, not a path to executable. Although if that is the case, perhaps we should add a `_dir` or `_directory` suffix for fixture name (and CLI option)?

### CODE REVIEW

**Comment by youtux** [comment]
It seems to me that the `splinter_webdriver_executable` fixture/config option is only used for the Chrome browser, and in that case it seems to be the path to the `chromedriver` executable, not the parent directory.

Using the path to the executable the test works:
```
$ pytest  --splinter-webdriver=chrome --splinter-webdriver-executable=/usr/local/bin/chromedriver tests/test_plugin.py::test_browser
======================================== test session starts ========================================
platform darwin -- Python 2.7.15, pytest-3.10.1, py-1.7.0, pluggy-0.8.1 -- /Users/youtux/Developer/pytest-splinter/.env/bin/python2.7
cachedir: .pytest_cache
rootdir: /Users/youtux/Developer/pytest-splinter, inifile: tox.ini
plugins: xdist-1.26.1, localserver-0.5.0, forked-1.0.1, cov-2.6.1, pylama-7.6.6, splinter-2.0.1
collected 1 item

tests/test_plugin.py::test_browser PASSED                                                     [100%]

===================================== 1 passed in 2.39 seconds ======================================
```

Using the directory of chromedriver (`/usr/local/bin/` in my case) fails because it is trying to execute that path:
```
$ pytest  --splinter-webdriver=chrome --splinter-webdriver-executable=/usr/local/bin/ tests/test_plugin.py::test_browser
======================================== test session starts ========================================
platform darwin -- Python 2.7.15, pytest-3.10.1, py-1.7.0, pluggy-0.8.1 -- /Users/youtux/Developer/pytest-splinter/.env/bin/python2.7
cachedir: .pytest_cache
rootdir: /Users/youtux/Developer/pytest-splinter, inifile: tox.ini
plugins: xdist-1.26.1, localserver-0.5.0, forked-1.0.1, cov-2.6.1, pylama-7.6.6, splinter-2.0.1
collected 1 item

tests/test_plugin.py::test_browser ERROR                                                      [100%]

============================================== ERRORS ===============================================
__________________________________ ERROR at setup of test_browser ___________________________________

request = <SubRequest 'browser' for <Function 'test_browser'>>
...
            elif err.errno == errno.EACCES:
                raise WebDriverException(
                    "'%s' executable may have wrong permissions. %s" % (
>                       os.path.basename(self.path), self.start_error_message)
                )
E               WebDriverException: Message: 'bin' executable may have wrong permissions. Please see https://sites.google.com/a/chromium.org/chromedriver/home

cmd        = ['/usr/local/bin', '--port=50494']
err        = OSError(13, 'Permission denied')
self       = <selenium.webdriver.chrome.service.Service object at 0x105da04d0>

.env/lib/python2.7/site-packages/selenium/webdriver/common/service.py:88: WebDriverException
====================================== 1 error in 0.19 seconds ======================================
```

**Comment by cddumanov** [comment]
God damn! Please

**Comment by bubenkoff** [comment]
@cddumanov did you read @youtux comment?

**Comment by bubenkoff** [comment]
please what?
Alessio commented that if that's the directory, it's not true in all cases,
so please check for all corner cases

**Pull request closed without merging**
