### PR TITLE
Fix build failures

### PR DESCRIPTION
**Pull request by pelme**
This change is [Reviewable](https://reviewable.io/reviews/pytest-dev/pytest-splinter/80)

### CODE REVIEW

**Comment by pelme** [comment]
@peterlauri can you review/accept this PR on reviewable? :)

**Comment by nip3o** [comment]
Reviewed 1 of 1 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pytest-dev/pytest-splinter/80)*

**Comment by bubenkoff** [comment]
thanks!

**Comment by peterlauri** [comment]
@pelme sorry, has been on eastern holidays here in Sweden, but I see it is already merged so review is not needed, right?

**Pull request merged**
