### PR TITLE
build(setup.py): Add `project_urls` for PyPI

### PR DESCRIPTION
**Pull request by tony**
Add [`project_urls`](https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#project-urls) to _setup.py_

For [pytest-splinter's PyPI page](https://pypi.org/project/pytest-splinter/) to get easy links to project pages:
image

### CODE REVIEW

**Comment by tony** [comment]
@pytest-dev/pytest-splinter-admin  Anyone willing to approve?

**Review by mpasternak — APPROVED** [review]
I have manually checked every single URL and I must say they all seem proper. Approved, thanks.

**Comment by mpasternak** [comment]
Looks like this won't work, I'm unable to merge, because it waits for non-existent CI. 

I don't have admin privs but looks like this could be disabled for now and then fixed with GitHub Actions...

**Comment by tony** [comment]
@mpasternak Thank you for the review!

This is a tricky one.  I wonder what the next step is (hopefully this doesn't have to wait until a new CI is up, though that probably needs a PR too)

@pytest-dev/pytest-splinter-admin: Any thoughts on a next step? Anyone have the ability to override? (even if its a future CI PR)

**Pull request merged**
