### PR TITLE
Add command-line option --splinter-webdriver-executable

### PR DESCRIPTION
**Pull request by sureshvv**
For phantomjs/chrome drivers

### CODE REVIEW

**Comment by bubenkoff** [comment]
2 things:
- there are commits from unrelevant PR, which is implemented already, so please remove those
- can't it just be solved via PATH variable when running pytest?

**Comment by sureshvv** [comment]
OK.. May be not needed.

**Comment by bubenkoff** [comment]
please rebase to origin/master

**Comment by sureshvv** [comment]
Just learning git. Do not know about rebasing. But have made a new commit with just the changes. Let me know if any changes are needed.

**Comment by bubenkoff** [comment]
run this
```
git remote add upstream git@github.com:pytest-dev/pytest-splinter.git
git branch --set-upstream-to=upstream/master
git checkout -b webdriver-executable
git rebase -i origin/master  # follow the instructions
git push origin webdriver-executable
# edit PR on github to use this branch
```

**Comment by bubenkoff** [comment]
and for future, don't do features directly on master, create branches

**Comment by blueyed** [comment]
> # edit PR on github to use this branch

That's not possible.  A new PR would be required.
But you can force-push it to your master.

@sureshvv 
If you have your commit with only the changes already, you can also use that by cherry-picking it directly:

    # Create a new branch, based on origin/master
    git checkout -b splinter-webdriver-executable origin/master
    # Cherry-pick the commit from your other branch
    git cherry-pick fa4dc1e
    # Push it to your master, overwriting what is there
    git push -f sureshvv splinter-webdriver-executable:master

This will update this PR (which is using your `master` branch).

@bubenkoff is right in that you should always use a branch for your PRs, which makes it easier to change/rebase them.

**Comment by blueyed** [comment]
I recommend using https://github.com/github/hub btw, which provides additional commands to interface with Github.

@bubenkoff 
You could also cherry-pick the commit or squash-merge them into master directly.  But then it's also good for @sureshvv to learn this.. :)

**Comment by bubenkoff** [comment]
yep, that's why i tried to instruct him :)

On 12 April 2015 at 14:49, Daniel Hahler <notifications@github.com> wrote:

> I recommend using https://github.com/github/hub btw, which provides
> additional commands to interface with Github.
>
> @bubenkoff <https://github.com/bubenkoff>
> You could also cherry-pick the commit or squash-merge them into master
> directly. But then it's also good for @sureshvv
> <https://github.com/sureshvv> to learn this.. :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pytest-dev/pytest-splinter/pull/23#issuecomment-92054346>
> .
>



-- 
Anatoly Bubenkov

**Comment by sureshvv** [comment]
Another pull request with single commit has been created now.

**Pull request closed without merging**
