### PR TITLE
Headless Firefox

### PR DESCRIPTION
**Pull request by mpasternak**
Hi,

after `splinter` gets the change from https://github.com/cobrateam/splinter/issues/677 commited, this patch will give you headless Firefox.

### CODE REVIEW

**Comment by bubenkoff** [comment]
@mpasternak as it's merged looks like, will you bump the splinter version up in the requirements?

**Comment by mpasternak** [comment]
@bubenkoff I'd love to, but the version in splinter repo is 0.13.0 (changed 4 months ago) and it is also the latest version on PyPI. I guess the next pytest-splitner version will be 0.13.1 or 0.14.0. Looks like I need to change pytest-splinter requirements to "splinter>0.13.0", is that okay with you? This will effectively block working releases of pytest-splinter until splinter gets the new release done...

**Comment by mpasternak** [comment]
@bubenkoff Hey, how are things. Any progress on this issue? Looks like someone else also submitted a PR about --headless for Firefox...

**Comment by bubenkoff** [comment]
sorry for the late response, on your question about splinter>0.13.0 -> definitely a good idea then, please proceed

**Comment by mpasternak** [comment]
Splinter version bumped, please re-review

**Review by bubenkoff — CHANGES_REQUESTED** [review]
please add a changelog record and add yourself to authors

**Review by bubenkoff — CHANGES_REQUESTED** [review]
please add a changelog record and add yourself to the authors and resolve the conflicts

**Comment by mpasternak** [comment]
@bubenkoff Done, thanks

**Comment by bubenkoff** [comment]
@mpasternak broken tests?

**Comment by bubenkoff** [comment]
@mpasternak also looks like in the PR it displays the changes which are already in master

**Comment by mpasternak** [comment]
What do you mean "PR displays changes which are already in master"? 

I remember that I saw some headless Firefox patches merged from #123 , are those this changes you're talking about? 

I did --rebase, but I don't have much experience with it. If there's anything that I broke let me know. Should I remove my fork and re-apply those patches?

**Comment by bubenkoff** [comment]
if you look here: https://github.com/pytest-dev/pytest-splinter/pull/144/files, you'll see the changes definitely not made by you
so please rebase your branch correctly
https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request

**Comment by bubenkoff** [comment]
@mpasternak linters still fail - the easiest fix is just to run black over the code:
```
black tests pytest_splinter
```

**Comment by mpasternak** [comment]
TBH this trivial and small change because of my lack of knowledge how rebase works grew up to be a much harder problem. 

Would you suggest re-starting this branch again from scratch or is it still salvageable at this point? What's your idea on that?

**Comment by zupo** [comment]
@mpasternak: if you give me (`zupo`) push permissions on your fork, I can try doing the rebasing for you.

**Comment by bubenkoff** [comment]
@mpasternak tests are failing please check

**Comment by zupo** [comment]
I've reapplied changes proposed in this PR on top of latest master and opened a new PR: https://github.com/pytest-dev/pytest-splinter/pull/152

**Comment by mpasternak** [comment]
Thanks @zupo, I hope this gets committed

**Comment by bubenkoff** [comment]
implemented in 3.3.0

**Pull request closed without merging**
