### PR TITLE
support latest pytest. closes #69

### LINKED ISSUE #69: pytest 3.0 compatibility
Running the 3.0 prerelease, pytest-splinter fails with:

```
__________________ ERROR at teardown of test_stupid_test[0] _________________

request = <SubRequest 'browser_screenshot' for <Function 'test_stupid_test[0]'>>, splinter_screenshot_dir = '<redacted>'
session_tmpdir = local('/private/var/folders/2w/bh7b385124b2wy0vkkcv0s9w0000gn/T/pytest-of-<redacted>'), splinter_make_screenshot_on_failure = True, splinter_screenshot_encoding = 'utf-8'
splinter_screenshot_getter_png = <function getter at 0x114d0ad70>, splinter_screenshot_getter_html = <function getter at 0x114d0ade8>

    @pytest.yield_fixture(autouse=True)
    def browser_screenshot(
            request, splinter_screenshot_dir, session_tmpdir, splinter_make_screenshot_on_failure,
            splinter_screenshot_encoding, splinter_screenshot_getter_png, splinter_screenshot_getter_html):
        """Make browser screenshot on test failure."""
        yield
>       for name, value in request._funcargs.items():
E       AttributeError: SubRequest instance has no attribute '_funcargs'

venv-2.7/lib/python2.7/site-packages/pytest_splinter/plugin.py:439: AttributeError

```

### PR DESCRIPTION
**Pull request by bubenkoff**
This change is [Reviewable](https://reviewable.io/reviews/pytest-dev/pytest-splinter/70)

### CODE REVIEW

**Comment by bubenkoff** [comment]
ok i checked and it works
please review, merge and release to pypi :)

**Comment by pelme** [comment]
Thanks Anatoly.

I just ran my full test suite with pytest 3.0.0, pytest-django@master and this pytest-splinter@pytest-latest-support and everything just worked. :)

**Comment by pelme** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pytest-dev/pytest-splinter/70)*

**Comment by pelme** [comment]
Didn't realize I had pypi access to pytest-splinter. I've put out a new release now, I did a quick test on the distribution locally before I pushed it to PyPI, I hope it works 😅

**Comment by bubenkoff** [comment]
Thanks!

**Pull request merged**
